### PR TITLE
support for maxlength attribute

### PR DESCRIPTION
**Pull request by pauloamgomes**
#647 Adding support for maxlength on text field

### CODE REVIEW

**Comment by aheinze** [comment]
Thank you for the contribution! would be great to have also support for min length, pattern etc.

**Comment by pauloamgomes** [comment]
Yeah, it make sense, the same structure can be used for the field definition, e.g.:

input-attributes-1

or we can have an attributes attribute and just iterate over it and set them:

text-attributes-2

**Comment by pauloamgomes** [comment]
In the meantime updated the PR to support multiple attributes:

cockpit-textfield-attributes

That will result in the proper validations, e.g.:

pattern-fail

**Comment by aheinze** [comment]
sorry, but I prefer the old way ... thanks again!

**Comment by pauloamgomes** [comment]
Ok, but you mean having the maxlength, minlength and pattern on the root definition? Or you don't want at all the change?

**Comment by aheinze** [comment]
On the root definition, the change is great and needed!

**Pull request closed without merging**
