### PR TITLE
added event for manipulate admin find options

### PR DESCRIPTION
**Pull request by pauloamgomes**
#1135  Having the event here is handy as can provide to the users further search in other fields than the title.

### CODE REVIEW

**Comment by aheinze** [comment]
could you describe a use-case?

**Comment by pauloamgomes** [comment]
I have a collection that I need editors to search by referenced contents.
Or search by slug.

**Comment by aheinze** [comment]
could you then also please add an `collections.admin.find.after.{$collection['name']}` event. Thanks.

**Comment by aheinze** [comment]
Thanks!

**Pull request merged**
