### PR TITLE
Extract license from README.md, apply copyright file headers

### PR DESCRIPTION
**Pull request by Crease29**
Hello Artur,

I've extracted the license out of the README and added it to an own file so that GitHub will display the license on the repository page like this:

image

Also, regarding to the license, I've added the copyright to all PHP files with PHP-CS-Fixer. I hope this new dev dependency is okay for you. Is there any fixed codestyle? If so, I could also provide a configuration for PHP-CS-Fixer to fix all files and check them with a pre-commit hook.

Would it also make sense to set the copyright information to `2019` instead of `2015`?

Cheers

### CODE REVIEW

**Comment by aheinze** [comment]
Hi!

Thank you for you contribution. But this is a huge PR. I would like to merge the license part. but I'm against the php-cs-fixer inclusion as a vendor requirement (would rather prefer to use a globally installed php-cs-fixer version) .

**Comment by Crease29** [comment]
That means I should just remove the part from `lib/vendor/`, `composer.json` and `composer.lock`?

**Comment by aheinze** [comment]
Ja bitte :-)

**Comment by Crease29** [comment]
Sorry, my change to the comment has overlapped with your answer. Could you please comment on that?

**Comment by teiling88** [comment]
Hey Guys,
I think your solution for that is phar.io / phive. Feel free to have a look into my blog post about it. 
If you have further questions feel free to contact me :-)

**Comment by Crease29** [comment]
Thanks @teiling88, that seems to be a better way to organize dev tool dependencies. Maybe I'll try to introduce that and the benefits in a different PR :slightly_smiling_face:

**Comment by aheinze** [comment]
can you adjust the header to 

```
/*
 * This file is part of the Cockpit project.
 *
 * (c) Artur Heinze - Agentejo, http://agentejo.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```

Thanks!

**Comment by Crease29** [comment]
Done. I squashed all of the commits so we have a cleaner history after merging this. :slightly_smiling_face:

**Comment by aheinze** [comment]
Just saw that `lib/vendor/composer/ClassLoader.php` is still in the commit

**Comment by Crease29** [comment]
Thanks for checking. I've fixed that.

**Comment by aheinze** [comment]
Thanks!

**Pull request merged**
