### PR TITLE
Improves Defining CLI Constant In bootstrap.php

### PR DESCRIPTION
**Pull request by funkvn**
* Uses identical operator
* Adds a block to if statement (recommended by PSR-2)

Hints comes from Php Inspections (EA Extended) too.

### CODE REVIEW

**Comment by funkvn** [comment]
Just a minor change to test the workflow. :-)

**Comment by funkvn** [comment]
OK, the change was intendet to merge too.
What do you think about the code?

**Comment by aheinze** [comment]
Thank you for the contribution. But this PR is just a code style preference. Also there is no need for `===` as the value of `PHP_SAPI` is always a string

**Comment by funkvn** [comment]
Thanks for your reply. 

So I will argue the other way around: `PHP_SAPI` is always a string so you do not need a loose comparison. 

`===` is more clear (it says, that a string is expeced, and here it is) and faster (https://stackoverflow.com/questions/2401478/why-is-faster-than-in-php; http://www.phpbench.com/)&mdas;and that's why it is recommended (e. g.) by the PHP Inspections.

To code style again: why not using a common standard as PSR-2? I was really skeptical but over the years this was a big step for code interchange, simplifying the settings settings and easier contribution.  :-)

**Pull request closed without merging**
