### PR TITLE
Expose parent options to nested Layouts/LayoutComponents

### PR DESCRIPTION
**Pull request by ebspeter**
Exposing settings being added in agentejo/LayoutComponents#4.

### CODE REVIEW

**Comment by aheinze** [comment]
Hi, any reasons behind this PR?

**Comment by ebspeter** [comment]
That's quick, and thanks for an awesome project! The preview functionality is crazy. 

Yes, it's related to two other PR's: agentejo/LayoutComponents#4. and pauloamgomes/Cockpit-CustomComponents#4. 

My LayoutComponents that accepts nested children only import selected components on the front-end app. So i need to control user input to not be able to nest an unsupported LayoutComponent. 

Example:
Background, Reviews, ImageLeft, etc. are all LayoutComponents in Cockpit. Since i don't want to import all other components in Background.vue i want to limit the user input to the supported ones. 

Background.vue: 
```vue
<template>
  <div class="wrapper" :class="parallax && 'parallax'">
    <div class="background" />
    <div class="overlay" />
    <div class="content">
      <template v-for="({settings, component, children: nestedChildren}, ckey) in children">
        <component :is="component" :key="'c' + ckey" v-bind="settings" :children="nestedChildren" />
      </template>
    </div>
  </div>
</template>

<script>
export default {
  components: {
    Reviews: () => import('@/components/Reviews'),
    ImageLeft: () => import('@/components/Cards/ImageLeft'),
    ImageTop: () => import('@/components/Cards/ImageTop'),
    ScrollCTA: () => import('@/components/CTA/Scroll'),
    LinkCTA: () => import('@/components/CTA/Link'),
    CardReviews: () => import('@/components/Reviews/CardReviews')
  },
  props: {
    parallax: {
      type: Boolean,
      default: false
    },
    children: {
      type: Array,
      default: () => []
    }
  }
}
</script>

<style lang="scss" scoped>
    ...styles
</style>
```

**Comment by fredrikkarlsson-pervanovo** [comment]
I also need this feature. My case is creating a table component which can only contain row components, which can only contain column components, which can only contain certain components.

@aheinze Any reason for this not to be merged?

**Comment by aheinze** [comment]
Thanks for the contribution!

**Comment by ebspeter** [comment]
Glad to contribute.Again, thanks for an awesome project!

**Comment by aheinze** [comment]
Sorry, I had to revert it. 😕 I'll try to figure out to add that functionality

**Comment by ebspeter** [comment]
Alright, I'm sure there are better ways. If you let me know what's wrong I'm happy to try to improve the PR.

Then I can also update the related PR's if needed.

**Comment by fredrikkarlsson-pervanovo** [comment]
What went wrong with this PR?

**Pull request merged**
