### PR TITLE
support for default attribute

### PR DESCRIPTION
**Pull request by pauloamgomes**
Support for default on fields select, text, textarea and rating - Issue #965

### CODE REVIEW

**Comment by pauloamgomes** [comment]
Reopen as changes on setting defaults seems to work with custom components.

**Comment by pauloamgomes** [comment]
@aheinze , when you can, kindly confirm if that make sense, I'm working in an implementation that uses custom components and having defaults (checkboxes, dropdowns, etc..) is mandatory. Tbh not sure why defaults work on collections but not on custom components, but forcing the verification and update on each field seems to solve it.

**Comment by aheinze** [comment]
I need some time to figure this out. A generic solution for ALL fields would be cool. maybe extend/improve the `cp-field` component 🤔

**Comment by aheinze** [comment]
awesome find! thank you!

**Pull request merged**
