### PR TITLE
Feature/webhook triggers autocomplete

### PR DESCRIPTION
**Pull request by gobeli**
I was a bit frustrated to figure out which triggers exist for webhooks, so I created an autocomplete in the webhook panel:

autocomplete

I wasn't exactly sure where to put the list (I used the one from #661). Maybe it would be cool to even load it dynamically with the collection/singelton/form names... 

If you are interested to add this feature I would appreciate feedback, which I would be happy to implement.

### CODE REVIEW

**Comment by aheinze** [comment]
Thanks for the contribution!

**Comment by pauloamgomes** [comment]
@aheinze , think it may be a problem for triggers that have a dynamic value like the collections.find.after{$name}:

image

I'm not able to change it anymore

**Comment by aheinze** [comment]
@pauloamgomes should be fixed now with this commit: https://github.com/agentejo/cockpit/commit/49f6b1d50713839619e519e71f8e8d1e5f9ebda7

**Comment by gobeli** [comment]
I think it would be cool if the name placeholders would get filled out dynamically with the collection/singelton/form names unfortunately I don't know the project well enough to implement that...

**Pull request merged**
