### PR TITLE
Added a Kubernetes Helm Chart

### PR DESCRIPTION
**Pull request by beasteers**
I needed to add Cockpit to my Kubernetes cluster so I added a Helm Chart for it. Kubernetes support was requested in #1082 so hopefully people find this useful! 

To run:
```bash
# create your config
cp ./charts/cockpit/values.yml cockpit.values.yml  # NOTE copy don't modify directly
# customize  cockpit.values.yml

# install
helm install cockpit ./charts/cockpit -f cockpit.values.yml
# if you're using the default repo, go to /install to add your admin user
```

How your values.yml file could look:
```yaml
# this gets put in config/config.yaml
config:
  app.name: My super cool thing
  site_url: https://mydomain.com
  il8n: tr  # FYI this will be downloaded as well if its not already in `languages`
  ...  # https://getcockpit.com/documentation/reference/configuration

languages:  # languages to install
  - UA_uk  # Українська
  - cs     # Čeština
  - de     # Deutsch
  - es     # Español
  - fr     # Français
  ...  # https://github.com/agentejo/cockpit-i18n

# enables admin user autoinstall (see PR #1257) so you don't have to go to /install
image:
  repository: beasteers/cockpit # default: agentejo/cockpit
  tag: latest

extraEnv: # {}
  # only for beasteers/cockpit
  COCKPIT_ADMIN_USER: asdf
  COCKPIT_ADMIN_NAME: Asdf Asdf
  COCKPIT_ADMIN_PASSWORD: asdfasdfasdf  # WILL ONLY AUTOINSTALL IF THIS IS SET
  COCKPIT_ADMIN_EMAIL: asdf@asdf.com
  # this can be used with the default image
  COCKPIT_SALT: asddfasdfasdf
```

Look in the [README](https://github.com/beasteers/cockpit/tree/k8s-helm/charts/cockpit) and [values.yml](https://github.com/beasteers/cockpit/blob/k8s-helm/charts/cockpit/values.yaml) for the full set of options.

TODO:
 - ~add persistence (probably with a stateful set? but honestly idk)~
 - merge #1257 so that `/install` can be configured thru environment variables and run automatically
 - for fun:
     - add a "CockpitCollection" custom resource definition (and maybe Form/Singleton, though tbh I've never used either) and APIKey / Webhook

### CODE REVIEW

**Comment by beasteers** [comment]
I changed cockpit to a statefulset and now things persist. Yay!

**Comment by aheinze** [comment]
Thank you @beasteers ! But I think it would make more sense if you create a dedicated repository for this and use cockpit as eg a submodule.

**Comment by beasteers** [comment]
Yeah that's a good point, I'll do that! 

For the official Cockpit docker image, are you using the Dockerfile in this repo? or the cockpit-docker repo?

**Comment by beasteers** [comment]
Done! The helm chart now lives at https://github.com/beasteers/cockpit-helm.

Let me know if you want to pull it under the official namespace and I'd be happy to stay on as a maintainer. I guess I'll just close this for now

**Pull request closed without merging**
