### PR TITLE
Fix #1074

### LINKED ISSUE #1074: [security] Filters are not being applied when pointing directly to the admin entry URL
Hi, I realized that if I go directly to the entry URL from the admin panel my filters (collection.read.php) don't take effect, they work on the lists, counters, etc. but not when going directly to the URL, Am I missing something?

I created a custom group and enabled just the View Entries permission. I'm using MongoDB.

E.g. URL: /collections/entry/articles/5ca76d2ea4c0a53a443cbd20

I guess that this happens because **Collections\Controller\Admin->entry()** doesn't do any filtering?

I realized that collection.read.php gets executed but 'too late'.

Thank you.

### PR DESCRIPTION
**Pull request by filisko**
This would fix #1074

### CODE REVIEW

**Comment by aheinze** [comment]
Thanks for the contribution. Need to check first if there are some side-effects

**Comment by filisko** [comment]
Yes, side-effects are the main concern. 👍

**Comment by filisko** [comment]
No updates on this? :thinking:

**Comment by aheinze** [comment]
Thanks again!

**Pull request merged**
