### PR TITLE
Feature 863 extensions

### PR DESCRIPTION
**Pull request by pauloamgomes**
PR contains minimal changes in core that can provide the functionality requested on #863

### CODE REVIEW

**Comment by pauloamgomes** [comment]
@aheinze , any idea if you go ahead with that solution, or you are thinking about something different? The current solution seems simple enough and doesn't cause any regression.

**Comment by aheinze** [comment]
Hi Paulo,

can we change the settings to:

```
modules:
    disabled: [...listOfModules]
```

I think that it makes more sense to define the disabled modules instead of naming the enabled.
What do you think?

Greets
Artur

**Comment by mpartipilo** [comment]
I like how GatsbyJS lets you specify exactly which plugins to use and pass an options object to the plugin instance. Even multiple instances of a plugin can be used with different options.

**Comment by pauloamgomes** [comment]
@aheinze yeah, that can also work and means we don't need to specify the core modules in the code, my initial thinking was based on the idea of enabling a module would require always a user action in the configuration (to avoid for example an addon causing  an error until is properly installed)

**Comment by pauloamgomes** [comment]
Think now is more cleaner, but we need a different key as modules is rewritten:

```yaml
modules.disabled:
  - Regions
  - Forms
  - ...
```

**Comment by aheinze** [comment]
Thanks!

**Pull request merged**
